FROM node:20-alpine

WORKDIR /app

# Install dependencies only when needed
RUN apk add --no-cache libc6-compat

# Copy package files
COPY package.json package-lock.json* ./
COPY prisma ./prisma/

# Install all dependencies (including devDependencies)
RUN npm install

# Rebuild the source code only when needed
COPY . .

# Generate Prisma client
RUN npx prisma generate

# Exposition of the port
EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

# Start the application in development mode with hot-reloading
CMD ["npm", "run", "dev"]
